### PR TITLE
Milestone 1

### PR DESCRIPTION
**Pull request by Israel-Laguan**
# Resume

I've followed the specifications as described in the project requirements, added the event listeners, passed props and connect to buttons, and *came to the conclusion that I met all of the requirements*.

# Proposal

I want to have a review of the code to know if I need to make any changes. If no changes needed I want the project to be ACCEPTED so I can move to the next project with a happy smile :)

# Specifications

- Followed [these requirements](https://github.com/microverseinc/project-redux-bookstore/blob/master/milestones/MILESTONE_1.md) for Milestone 1
- Uses `create-react-app` to initialize the new React app 
- Added `react-redux` & `redux`
- Added `ESlint` & `Jest`
- Served from Heroku

# Live Version Here

[image](https://owly-bookstore.herokuapp.com/)

# Tests

### `ESLint`
image

### `Jest`
image

### CODE REVIEW

**Review by bellom — CHANGES_REQUESTED** [review]
## Hi @Israel-Laguan  :clap: 

### Awesome job so far!! :+1: 

### May I know the reason why you're working alone on a collaborative project?

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 

**_1.  Kindly delete unnecessary files and asset;_**
image
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896806/

**_2. Kindly add `prop-types` to your `package.json` file;_**
image
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896806/

**Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....**

Best,

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

**Comment by Israel-Laguan** [comment]
Hi @bellom ! About your review: 
> **_1. Kindly delete unnecessary files and asset;_**
> image

In fact I am using ALL of the files, but I can drop some files in order to met this requirement.

> https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896806/
> 
> **_2. Kindly add `prop-types` to your `package.json` file;_**
> image
> https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896806/
> 
Oops, I'll add it now!

Thanks for your review!

**Comment by bellom** [comment]
> ## Hi @Israel-Laguan 👏
> ### Awesome job so far!! 👍
> ### May I know the reason why you're working alone on a collaborative project?
> #### You have done wonderfully well, you passed `almost` all the checklist for this project 👍 just a few issues left to work on............ 🙂
> **_1. Kindly delete unnecessary files and asset;_**
> image
> https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896806/
> 
> **_2. Kindly add `prop-types` to your `package.json` file;_**
> image
> https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896806/
> 
> **Kindly re-submit for review after making all those changes 🙂 Thumps -up await you.....**
> 
> Best,
> 
> **Oluwaseun Bello**
> **_Slack Handle - @sean bellom_**

@Israel-Laguan 
I guess you missed this 👉 **May I know the reason why you're working alone on a collaborative project?**

**Review by bellom — APPROVED** [review]
## Hi Team :clap: 

**Great work making all the necessary corrections from the previous review.**

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Good luck in the next milestone :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

**Pull request merged**
